insert into categoria (codigo, nome, descricao) values (1, 'Livros e Galeria de Arte', 'Itens como Livros, Livros Importados, Livros Digitais (e-books), Galeria de Arte e Papelaria.');
insert into categoria (codigo, nome, descricao) values (2, 'Câmeras e Filmadoras', 'Itens como Câmeras Digitais, Cartões de Memória, Acessórios para Câmeras, Porta retrato Digital, Revelação Digital e Filmadoras.');
insert into categoria (codigo, nome, descricao) values (3, 'Notebooks e Computadores', 'Itens como Informática, Notebook, Ultrabook, Tablets e iPad, Computadores, Mochilas para Notebooks, Monitores LCD, HDs externos, Acessórios de Informática, Multifuncionais e Impressoras, Apple.');
insert into categoria (codigo, nome, descricao) values (4, 'Eletrodomésticos', 'Itens como Eletrodomésticos, Ar Condicionado e Aquecedores, Lavadora de Roupas, Secadora de Roupas, Geladeiras, Fogões, Coifas, Micro-ondas, Lava-louça, Adegas, Lavadoras de Pressão.');
insert into categoria (codigo, nome, descricao) values (5, 'TVs, Audio e Eletrônicos', 'Itens como TVs, Home Theater, Blu-ray player, Audio, Fones de Ouvido, Automotivo e GPS.');

insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 1, 'A saga que atravessou o espaço e inúmeras gerações de fãs retorna ao público brasileiro em grande estilo.', 'Livro - Star Wars: A Trilogia - Special Edition', 50.31);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 1, 'O clássico filme criado por Steven Spielberg, Os Goonies, volta direto dos anos 1980 em um livro inesquecível, criado durante o processo de produção e filmagens.', 'Livro - Os Goonies: Special Edition', 60.89);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 2, 'Câmera Digital Semi-Profissional Nikon L320 16MP Zoom óptico 26x Cartão 4 GB - Preta', 'Câmera Digital Semi-Profissional Nikon L320', 599.00);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 2, 'Câmera Digital Sony DSC-HX300 20.4 MP, Zoom Óptico de 50x + Cartão de Memória de 8GB', 'Câmera Digital Sony DSC-HX300', 1790.00);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 3, 'Notebook Ultrafino HP Pavilion 14-n050br com Intel Core i7 8GB (2GB de Memória Dedicada) 1TB LED 14" Windows 8', 'Notebook Ultrafino HP Pavilion 14-n050br', 2699.60);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 3, 'Mac Mini MD388BZ/A com Intel Core i7 4GB 1TB OS X Mountain Lion 10.8 - Apple', 'Mac Mini MD388BZ/A', 3779.10);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 4, 'Lavadora de Roupa Electrolux LTE12 - 12kg Turbo Economia - Branca', 'Lavadora de Roupa Electrolux', 1206.60);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 4, 'Geladeira / Refrigerador Frost Free Brastemp Clean BRM39 - 352 Litros - Inox', 'Geladeira / Refrigerador Frost Free Brastemp', 1949.90);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 5, 'Smart TV 3D LED 47" LG 47LA6204 Full HD 3 HDMI 3 USB 120Hz 4 Óculos 3D', 'Smart TV 3D LED 47" LG 47LA6204 Full HD', 2359.00);
insert into produto (codigo, categoria_codigo, descricao, nome, valor) values (default, 5, 'Blu-Ray Player 3D Samsung BD-F5500/ZD', 'Blu-Ray Player 3D Samsung', 318.00);